#!/usr/bin/env python3
"""Clone celestial's per-color `@if $color == "aliz"` SCSS blocks for new colors.

For each `_colors.scss` file, every top-level `@if ... $color == "aliz" ...`
block is duplicated for each new color, renaming aliz -> <color> and replacing
the accent literal #f0544c -> <hex>. Neutral darks and the success color are
inherited verbatim, so a new color is "aliz with a different accent". Inserted
blocks are wrapped in sentinel comments and re-generated idempotently.

Usage:
  arc-colors-scss.py <colors_tsv> <scss_file> [<scss_file> ...]

colors_tsv: lines of "<name>\t<hex>" (hex without '#').
"""
import re
import sys

SENTINEL = "// arc-colors-generated (do not edit; regenerated by generate-arc-colors.sh)"
ALIZ_OPEN = re.compile(r'^\s*@if\b.*\$color\s*==\s*"aliz"(\s+and\b.*)?\s*\{\s*$')
ACCENT = "#f0544c"


def load_colors(path):
    out = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, hexv = line.split()
        out.append((name, "#" + hexv.lstrip("#").lower()))
    return out


def strip_generated(lines):
    """Remove previously generated sentinel+block runs."""
    out, i, n = [], 0, len(lines)
    while i < n:
        if lines[i].strip() == SENTINEL:
            # skip sentinel + following @if block (until its closing '}' at col 0)
            i += 1
            if i < n and lines[i].lstrip().startswith("@if"):
                while i < n and lines[i].rstrip() != "}":
                    i += 1
                i += 1  # skip the closing '}'
            # swallow a single trailing blank line we inserted
            if i < n and lines[i].strip() == "":
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return out


def clone_block(block, name, hexv):
    out = [SENTINEL + "\n"]
    for ln in block:
        ln = ln.replace('"aliz"', f'"{name}"')
        ln = re.sub(re.escape(ACCENT), hexv, ln, flags=re.IGNORECASE)
        out.append(ln)
    out.append("\n")
    return out


def process(path, colors):
    lines = strip_generated(open(path, encoding="utf-8").readlines())
    out, i, n = [], 0, len(lines)
    while i < n:
        if ALIZ_OPEN.match(lines[i]):
            block = [lines[i]]
            i += 1
            while i < n and lines[i].rstrip() != "}":
                block.append(lines[i])
                i += 1
            if i < n:
                block.append(lines[i])  # closing '}'
                i += 1
            out.extend(block)
            out.append("\n")
            for name, hexv in colors:
                out.extend(clone_block(block, name, hexv))
        else:
            out.append(lines[i])
            i += 1
    open(path, "w", encoding="utf-8").write("".join(out))


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    colors = load_colors(sys.argv[1])
    for path in sys.argv[2:]:
        process(path, colors)


if __name__ == "__main__":
    main()
